from __future__ import annotations

from stream_kernel.execution.orchestration.scheduler_system_nodes import (
    SCHEDULER_COMMAND_NODE_NAME,
    SCHEDULER_TIMER_NODE_NAME,
    SCHEDULER_TICK_NODE_NAME,
    PlatformSchedulerCommandNode,
    PlatformSchedulerTimerNode,
    PlatformSchedulerTickNode,
)
from stream_kernel.kernel.scenario import StepSpec

from .leaf_ingress_nodes import (
    ROOT_BOUNDARY_HANDOFF_SINK_NODE_NAME,
    ROOT_LEAF_CONTROL_DISPATCH_SINK_NODE_NAME,
)

ROOT_STATIC_SYSTEM_NODE_NAMES: tuple[str, ...] = (
    "system.cp.bootstrap_dispatch",
    "system.cp.root_bootstrap",
    SCHEDULER_COMMAND_NODE_NAME,
    SCHEDULER_TIMER_NODE_NAME,
    SCHEDULER_TICK_NODE_NAME,
    "system.cp.consumer_registry_bindings_bootstrap",
    "system.cp.consumer_registry_bindings_apply",
    "system.cp.deferred_message_hold",
    "system.cp.deferred_message_replay",
    "system.cp.root_config_stream",
    ROOT_LEAF_CONTROL_DISPATCH_SINK_NODE_NAME,
    "system.cp.root_stop_ack_state",
    ROOT_BOUNDARY_HANDOFF_SINK_NODE_NAME,
    "system.cp.consumer_registry_discovery_apply",
    "system.cp.consumer_registry_remove",
    "system.cp.discovery_pump",
    "system.cp.discovery_apply",
    "system.cp.discovery_materialize",
    "system.cp.discovery_finalize",
    "system.cp.system_config_apply",
    "system.cp.observability_config_apply",
    "system.cp.node_config_apply",
    "system.cp.config_apply_barrier",
    "system.cp.startup_barrier",
    "system.cp.dag_assembly",
    "system.cp.init_plan",
    "system.cp.initialization_plan",
    "system.cp.node_initialize",
    "system.cp.ready_for_work",
    "system.cp.consumer_registry_group_prune",
    "system.cp.shutdown_expected_groups",
    "system.cp.start_work_readiness",
    "system.cp.start_work_dispatch",
    "system.cp.start_work_command_dispatch",
    "system.cp.root_stop_dispatch",
    "system.cp.log_dispatch_sink",
    "system.cp.root_payload_sink",
    "system.cp.shutdown_leaf_ready",
    "system.cp.root_stop",
)


def build_root_static_system_steps(
    *,
    bootstrap_dispatch: object,
    root_bootstrap: object,
    consumer_registry_bindings_bootstrap: object,
    consumer_registry_bindings_apply: object,
    deferred_message_hold: object,
    deferred_message_replay: object,
    root_config_stream: object,
    root_reply_dispatch_sink: object,
    root_stop_ack_state: object,
    root_boundary_handoff_sink: object,
    consumer_registry_discovery_apply: object,
    consumer_registry_remove: object,
    discovery_pump: object,
    discovery_apply: object,
    discovery_materialize: object,
    discovery_finalize: object,
    system_config_apply: object,
    observability_config_apply: object,
    node_config_apply: object,
    config_apply_barrier: object,
    startup_barrier: object,
    dag_assembly: object,
    init_plan: object,
    initialization_plan: object,
    node_initialize: object,
    ready_for_work: object,
    consumer_registry_group_prune: object,
    shutdown_expected_groups: object,
    start_work_readiness: object,
    start_work_dispatch: object,
    start_work_command_dispatch: object,
    root_stop_dispatch: object,
    root_log_dispatch_sink: object,
    root_payload_sink: object,
    leaf_drain_ready: object,
    root_stop: object,
) -> list[StepSpec]:
    return [
        StepSpec(name="system.cp.bootstrap_dispatch", step=bootstrap_dispatch),
        StepSpec(name="system.cp.root_bootstrap", step=root_bootstrap),
        StepSpec(name=SCHEDULER_COMMAND_NODE_NAME, step=PlatformSchedulerCommandNode()),
        StepSpec(name=SCHEDULER_TIMER_NODE_NAME, step=PlatformSchedulerTimerNode()),
        StepSpec(name=SCHEDULER_TICK_NODE_NAME, step=PlatformSchedulerTickNode()),
        StepSpec(name="system.cp.consumer_registry_bindings_bootstrap", step=consumer_registry_bindings_bootstrap),
        StepSpec(name="system.cp.consumer_registry_bindings_apply", step=consumer_registry_bindings_apply),
        StepSpec(name="system.cp.deferred_message_hold", step=deferred_message_hold),
        StepSpec(name="system.cp.deferred_message_replay", step=deferred_message_replay),
        StepSpec(name="system.cp.root_config_stream", step=root_config_stream),
        StepSpec(name=ROOT_LEAF_CONTROL_DISPATCH_SINK_NODE_NAME, step=root_reply_dispatch_sink),
        StepSpec(name="system.cp.root_stop_ack_state", step=root_stop_ack_state),
        StepSpec(name=ROOT_BOUNDARY_HANDOFF_SINK_NODE_NAME, step=root_boundary_handoff_sink),
        StepSpec(name="system.cp.consumer_registry_discovery_apply", step=consumer_registry_discovery_apply),
        StepSpec(name="system.cp.consumer_registry_remove", step=consumer_registry_remove),
        StepSpec(name="system.cp.discovery_pump", step=discovery_pump),
        StepSpec(name="system.cp.discovery_apply", step=discovery_apply),
        StepSpec(name="system.cp.discovery_materialize", step=discovery_materialize),
        StepSpec(name="system.cp.discovery_finalize", step=discovery_finalize),
        StepSpec(name="system.cp.system_config_apply", step=system_config_apply),
        StepSpec(name="system.cp.observability_config_apply", step=observability_config_apply),
        StepSpec(name="system.cp.node_config_apply", step=node_config_apply),
        StepSpec(name="system.cp.config_apply_barrier", step=config_apply_barrier),
        StepSpec(name="system.cp.startup_barrier", step=startup_barrier),
        StepSpec(name="system.cp.dag_assembly", step=dag_assembly),
        StepSpec(name="system.cp.init_plan", step=init_plan),
        StepSpec(name="system.cp.initialization_plan", step=initialization_plan),
        StepSpec(name="system.cp.node_initialize", step=node_initialize),
        StepSpec(name="system.cp.ready_for_work", step=ready_for_work),
        StepSpec(name="system.cp.consumer_registry_group_prune", step=consumer_registry_group_prune),
        StepSpec(name="system.cp.shutdown_expected_groups", step=shutdown_expected_groups),
        StepSpec(name="system.cp.start_work_readiness", step=start_work_readiness),
        StepSpec(name="system.cp.start_work_dispatch", step=start_work_dispatch),
        StepSpec(name="system.cp.start_work_command_dispatch", step=start_work_command_dispatch),
        StepSpec(name="system.cp.root_stop_dispatch", step=root_stop_dispatch),
        StepSpec(name="system.cp.log_dispatch_sink", step=root_log_dispatch_sink),
        StepSpec(name="system.cp.root_payload_sink", step=root_payload_sink),
        StepSpec(name="system.cp.shutdown_leaf_ready", step=leaf_drain_ready),
        StepSpec(name="system.cp.root_stop", step=root_stop),
    ]


__all__ = [
    "ROOT_STATIC_SYSTEM_NODE_NAMES",
    "build_root_static_system_steps",
]
