from __future__ import annotations

from enum import Enum


# Stable internal reason codes are defined in docs/implementation/domain/Reason Codes.md.
class ReasonCode(str, Enum):
    INPUT_PARSE_ERROR = "INPUT_PARSE_ERROR"
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
    INVALID_AMOUNT_FORMAT = "INVALID_AMOUNT_FORMAT"
    INVALID_ID_FORMAT = "INVALID_ID_FORMAT"
    ID_DUPLICATE_REPLAY = "ID_DUPLICATE_REPLAY"
    ID_DUPLICATE_CONFLICT = "ID_DUPLICATE_CONFLICT"
    DAILY_ATTEMPT_LIMIT = "DAILY_ATTEMPT_LIMIT"
    DAILY_AMOUNT_LIMIT = "DAILY_AMOUNT_LIMIT"
    WEEKLY_AMOUNT_LIMIT = "WEEKLY_AMOUNT_LIMIT"
    PRIME_AMOUNT_CAP = "PRIME_AMOUNT_CAP"
    PRIME_DAILY_GLOBAL_LIMIT = "PRIME_DAILY_GLOBAL_LIMIT"
